### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by jichon** [couchbaselabs/cbfs#143]
Can't build do to go-counchbase update with package name changes. https://github.com/couchbase/go-couchbase/commit/94213df48fb5692b208a2d4fc7f8c1fab8667cc5#diff-36483a7174bd7c4d70f4e898a4ca0715

Here is the error output
./database.go:103: cannot use rv (type *"github.com/couchbaselabs/go-couchbase".Bucket) as type *"github.com/couchbase/go-couchbase".Bucket in argument to couchbaseutil.UpdateView

Needed to manually update the following lines in the database.go for a successful build

// Alias this because we call our connection couchbase
cb "github.com/couchbaselabs/go-couchbase"
"github.com/couchbaselabs/go-couchbase/util"

to

// Alias this because we call our connection couchbase
cb "github.com/couchbase/go-couchbase"
"github.com/couchbase/go-couchbase/util"

**Comment by tleyden** [comment]
Would you mind sending a PR for this?

**Comment by jichon** [comment]
resolved by #144
